name: matrix_dart_sdk_drift_db
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.22.1
  flutter:
    sdk: flutter
  matrix:
    git: 
      url: https://github.com/commetchat/matrix-dart-sdk.git
      ref: sdk-update
  path: ^1.9.0
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.15.7
  file: ">=6.1.1 <8.0.0"
  build_runner: ^2.4.10
  drift_dev: ^2.22.1


flutter:
